/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("EquipmentsObjectPageObjectPage journey");

        opaTest("Navigate to EquipmentsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheEquipmentsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheEquipmentsListGenerated.onTable().iCheckRows();
            When.onTheEquipmentsListGenerated.onTable().iPressRow(0);

            Then.onTheEquipmentsObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheEquipmentsObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "DataPoint::StatusHeader" });
            Then.onTheEquipmentsObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "DataPoint::OperatingHoursHeader" });
            Then.onTheEquipmentsObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "DataPoint::HealthScoreHeader" });
            Then.onTheEquipmentsObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "DataPoint::DailyRateHeader" });
            Then.onTheEquipmentsObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "FieldGroup::SupervisorHeader" });
            Then.onTheEquipmentsObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "SupervisorHeader",
                field: "supervisorName",
                targetAnnotation: ""
            });
            Then.onTheEquipmentsObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "SupervisorHeader",
                field: "supervisorEmail",
                targetAnnotation: ""
            });
            Then.onTheEquipmentsObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "SupervisorHeader",
                field: "supervisorPhone",
                targetAnnotation: ""
            });
        });

        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheEquipmentsObjectPageGenerated.iCheckNumberOfSections(3);
        });

        opaTest("Check the GeneralSection section of the Object Page", function (_Given, When, Then) {
            When.onTheEquipmentsObjectPageGenerated.iGoToSection({ section: "GeneralSection" });
            Then.onTheEquipmentsObjectPageGenerated.iCheckSection({ section: "GeneralSection" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "code" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "name" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "model" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "serialNumber" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "category_code" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "manufactureYear" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "imageUrl" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "status_code" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "location" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "operatingHours" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "healthScore" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "dailyRate" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "currency_code" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "lastServiceDate" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "nextServiceDate" });
        });

        opaTest("Check the MaintenanceSection section of the Object Page", function (_Given, When, Then) {
            When.onTheEquipmentsObjectPageGenerated.iGoToSection({ section: "MaintenanceSection" });
            Then.onTheEquipmentsObjectPageGenerated.iCheckSection({ section: "MaintenanceSection" });
        });

        opaTest("Check the AuditSection section of the Object Page", function (_Given, When, Then) {
            When.onTheEquipmentsObjectPageGenerated.iGoToSection({ section: "AuditSection" });
            Then.onTheEquipmentsObjectPageGenerated.iCheckSection({ section: "AuditSection" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "AuditSection" }).iCheckField({ property: "createdAt" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "AuditSection" }).iCheckField({ property: "createdBy" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "AuditSection" }).iCheckField({ property: "modifiedAt" });
            Then.onTheEquipmentsObjectPageGenerated.onForm({ section: "AuditSection" }).iCheckField({ property: "modifiedBy" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});