/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("EquipmentsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheEquipmentsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheEquipmentsListGenerated.onFilterBar().iCheckFilterField({ property: "category_code" });
            Then.onTheEquipmentsListGenerated.onFilterBar().iCheckFilterField({ property: "status_code" });
            Then.onTheEquipmentsListGenerated.onFilterBar().iCheckFilterField({ property: "location" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheEquipmentsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheEquipmentsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheEquipmentsListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheEquipmentsListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheEquipmentsListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheEquipmentsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"code":{"header":"Código"},"name":{"header":"Nombre de Equipo"},"category_code":{"header":"Categoría"},"status_code":{"header":"Estado Operativo"},"healthScore":{"header":"Salud (%)"},"operatingHours":{"header":"Horas Operación"},"dailyRate":{"header":"Tarifa Diaria"},"location":{"header":"Ubicación / Faena"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheEquipmentsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheEquipmentsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheEquipmentsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheEquipmentsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});