/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintenanceLogsObjectPageObjectPage journey");

        opaTest("Navigate to MaintenanceLogsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheEquipmentsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheEquipmentsListGenerated.onTable().iCheckRows();
            When.onTheEquipmentsListGenerated.onTable().iPressRow(0);

            Then.onTheEquipmentsObjectPageGenerated.iSeeThisPage();
            Then.onTheEquipmentsObjectPageGenerated.onTable({ property: "maintenanceLogs" }).iCheckRows();
            When.onTheEquipmentsObjectPageGenerated.onTable({ property: "maintenanceLogs" }).iPressRow(0);

            Then.onTheMaintenanceLogsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the FieldGroup::LogDetail section of the Object Page", function (_Given, _When, Then) {
            Then.onTheMaintenanceLogsObjectPageGenerated.iCheckSection({ section: "FieldGroup::LogDetail" });
            Then.onTheMaintenanceLogsObjectPageGenerated.onForm({ section: "FieldGroup::LogDetail" }).iCheckField({ property: "logNumber" });
            Then.onTheMaintenanceLogsObjectPageGenerated.onForm({ section: "FieldGroup::LogDetail" }).iCheckField({ property: "serviceDate" });
            Then.onTheMaintenanceLogsObjectPageGenerated.onForm({ section: "FieldGroup::LogDetail" }).iCheckField({ property: "maintenanceType" });
            Then.onTheMaintenanceLogsObjectPageGenerated.onForm({ section: "FieldGroup::LogDetail" }).iCheckField({ property: "technician" });
            Then.onTheMaintenanceLogsObjectPageGenerated.onForm({ section: "FieldGroup::LogDetail" }).iCheckField({ property: "hoursSpent" });
            Then.onTheMaintenanceLogsObjectPageGenerated.onForm({ section: "FieldGroup::LogDetail" }).iCheckField({ property: "cost" });
            Then.onTheMaintenanceLogsObjectPageGenerated.onForm({ section: "FieldGroup::LogDetail" }).iCheckField({ property: "currency_code" });
            Then.onTheMaintenanceLogsObjectPageGenerated.onForm({ section: "FieldGroup::LogDetail" }).iCheckField({ property: "status" });
            Then.onTheMaintenanceLogsObjectPageGenerated.onForm({ section: "FieldGroup::LogDetail" }).iCheckField({ property: "remarks" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});